#!/usr/bin/env node

const program = require('commander');
const pkg = require('./package.json');

program
  .version(pkg.version);


/*
|--------------------------------------------------------------------------
| Config
|--------------------------------------------------------------------------
*/
const configCommand = require("./src/commands/config");
program
  .command('config')
  .action(configCommand);


/*
|--------------------------------------------------------------------------
| Create
|--------------------------------------------------------------------------
*/
const newCommand = require("./src/commands/newCommand");
program
  .command('new <template> [path]')
  .action(newCommand);


/*
|--------------------------------------------------------------------------
| Templates
|--------------------------------------------------------------------------
*/
// program
//   .command('new <template> [path]')
//   .action(function (template, path) {
//   });


// program
//   .command('exec <cmd>')
//   .alias('ex')
//   .description('execute the given remote cmd')
//   .option("-e, --exec_mode <mode>", "Which exec mode to use")
//   .action(function(cmd, options){
//     console.log('exec "%s" using %s mode', cmd, options.exec_mode);
//   }).on('--help', function() {
//   console.log('');
//   console.log('Examples:');
//   console.log('');
//   console.log('  $ deploy exec sequential');
//   console.log('  $ deploy exec async');
// });
//

if (!process.argv.slice(2).length) {
  program.outputHelp();
}

program.parse(process.argv);